#Contains API Secret used to validate your application. Commit to internal source control; avoid making secret public.
#Wed Oct 07 07:33:25 CEST 2015
apiSecret=6bdb42de0ddace71056d6b560b1addf63bf8484b6e3e7f795d3575618322ff3f
