#Contains API Secret used to validate your application. Commit to internal source control; avoid making secret public.
#Sun Jan 29 04:33:09 CET 2017
apiSecret=f269c265532686e69336dead5e098be6015b0ae4e5d621be93a8f5a50ba267ab
